name: Upload Website

on:
  push:
    branches:
    - master
    - test-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name and set environment
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr -d '-')"
        BRANCH=${GITHUB_REF#refs/heads/}
