engines:
  csslint:
    enabled: true
  apexmetrics:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
  gnu-complexity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- "plugin/**/*"
- "roocms/lib/smarty/**/*"
- "roocms/lib/phpqrcode/**/*"
version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 1999
  method-lines:
    config:
      threshold: 199
  method-complexity:
    enabled: true
    config:
      threshold: 10
